/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./App.tsx', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        brand: {
          cyan: '#41D7FF',
          blue: '#0E86FF',
          lime: '#B7FF5A',
        },
        neutral: {
          0: '#FFFFFF',
          50: '#F8FBFF',
          100: '#F1F6FA',
          200: '#DDE6EE',
          300: '#C3D0DB',
          400: '#99AABA',
          500: '#667A89',
          600: '#4E6272',
          700: '#364A59',
          800: '#1F3240',
          900: '#0C1821',
          950: '#07111A',
        },
        background: 'var(--color-background, #F1F6FA)',
        surface: 'var(--color-surface, #FFFFFF)',
        card: 'var(--color-card, #FFFFFF)',
        input: 'var(--color-input, #FFFFFF)',
        border: 'var(--color-border, #DDE6EE)',
        foreground: 'var(--color-foreground, #0C1821)',
        muted: 'var(--color-muted, #667A89)',
        ring: 'var(--color-ring, #0E86FF)',
        primary: 'var(--color-primary, #0E86FF)',
        'primary-foreground': 'var(--color-primary-foreground, #061018)',
        'primary-soft': 'var(--color-primary-soft, #DDEEFF)',
        secondary: 'var(--color-secondary, #3EA864)',
        'secondary-foreground': 'var(--color-secondary-foreground, #F4FFF8)',
        'secondary-soft': 'var(--color-secondary-soft, #E6F7ED)',
        success: 'var(--color-success, #2F9E5A)',
        'success-foreground': 'var(--color-success-foreground, #F2FFF5)',
        'success-soft': 'var(--color-success-soft, #E9F8EE)',
        error: 'var(--color-error, #D44B60)',
        'error-foreground': 'var(--color-error-foreground, #FFF5F7)',
        'error-soft': 'var(--color-error-soft, #FBE8EC)',
        warning: 'var(--color-warning, #D4832F)',
        'warning-foreground': 'var(--color-warning-foreground, #FFF9F2)',
        'warning-soft': 'var(--color-warning-soft, #FFF1DF)',
        info: 'var(--color-info, #2B8AE6)',
        'info-foreground': 'var(--color-info-foreground, #F3F9FF)',
        'info-soft': 'var(--color-info-soft, #E8F2FD)',
      },
      fontFamily: {
        sans: ['System'],
        serif: ['Georgia'],
        mono: ['Courier New'],
      },
      fontSize: {
        caption: ['12px', {lineHeight: '16px'}],
        label: ['14px', {lineHeight: '20px'}],
        body: ['16px', {lineHeight: '24px'}],
        title: ['24px', {lineHeight: '32px'}],
        hero: ['30px', {lineHeight: '38px'}],
      },
      spacing: {
        1: '4px',
        2: '8px',
        3: '12px',
        4: '16px',
        5: '20px',
        6: '24px',
        8: '32px',
        10: '40px',
        12: '48px',
        16: '64px',
        18: '72px',
      },
      borderRadius: {
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
      },
      boxShadow: {
        'elevation-sm': '0 4px 12px rgba(12, 24, 33, 0.08)',
        'elevation-md': '0 12px 28px rgba(12, 24, 33, 0.14)',
        'elevation-lg': '0 18px 40px rgba(7, 17, 26, 0.18)',
      },
      maxWidth: {
        content: '420px',
        prose: '560px',
        page: '768px',
      },
    },
  },
  plugins: [],
};
