import type {Product} from './catalog';

export const ADDITIONAL_PRODUCTS: Product[] = [
  {
    id: 'jetson-orin-nano-dev-kit',
    code: 'JON',
    name: 'Jetson Orin Nano AI Dev Kit',
    vendor: 'NVIDIA',
    seller: 'Embedded Shop Labs',
    category: 'sbc',
    highlight: 'Compact AI compute for edge vision and robotics perception',
    shortDescription: 'CUDA-ready Orin Nano platform for camera pipelines and local inference.',
    overview:
      'Built for teams shipping embedded AI prototypes that need GPU acceleration, CSI camera support, and a software path into production edge inference workloads.',
    price: 6490000,
    previousPrice: 6990000,
    rating: 4.9,
    reviews: 118,
    stock: 9,
    availability: 'Low stock',
    leadTime: 'Ships in 48h',
    accent: '#7CFFB2',
    panel: '#122A21',
    specs: [
      {label: 'AI compute', value: 'Up to 40 TOPS'},
      {label: 'Memory', value: '8GB LPDDR5'},
      {label: 'Camera', value: 'MIPI CSI support'},
      {label: 'Connectivity', value: 'Gigabit Ethernet, USB 3.0'},
    ],
    tags: ['AI', 'Vision', 'Jetson'],
    applications: ['Object detection', 'Robot perception', 'Edge inference'],
    compatibility: ['ROS2', 'MIPI cameras', 'CUDA workflows'],
  },
  {
    id: 'beaglebone-black-industrial-controller',
    code: 'BBG',
    name: 'BeagleBone Black Industrial Controller',
    vendor: 'BeagleBoard',
    seller: 'Embedded Shop Labs',
    category: 'sbc',
    highlight: 'Industrial Linux controller board with rich real-time IO',
    shortDescription: 'Reliable AM335x board for gateways, machine IO, and deterministic edges.',
    overview:
      'A dependable single-board platform for industrial gateways and low-level machine interfaces where Linux flexibility and broad expansion matter more than raw GPU power.',
    price: 2290000,
    previousPrice: 2490000,
    rating: 4.6,
    reviews: 64,
    stock: 15,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#8BC3FF',
    panel: '#1A2538',
    specs: [
      {label: 'CPU', value: 'Sitara AM335x 1GHz'},
      {label: 'Memory', value: '512MB DDR3'},
      {label: 'Realtime', value: 'PRU industrial control cores'},
      {label: 'IO', value: 'GPIO, CAN, UART, SPI, I2C'},
    ],
    tags: ['Gateway', 'Industrial', 'Linux'],
    applications: ['Protocol bridge', 'Machine controller', 'Remote IO'],
    compatibility: ['Cape add-ons', 'RS485 modules', 'DIN enclosures'],
  },
  {
    id: 'orange-pi-5-max-edge-kit',
    code: 'OP5',
    name: 'Orange Pi 5 Max Edge Kit',
    vendor: 'Orange Pi',
    seller: 'Embedded Shop Labs',
    category: 'sbc',
    highlight: 'RK3588 edge board for vision, media, and gateway workloads',
    shortDescription: 'High-performance SBC with fast CPU cores and broad peripheral support.',
    overview:
      'A strong fit for edge UI, multi-camera bring-up, and local compute tasks where teams want high throughput without moving to a full x86 platform.',
    price: 4590000,
    previousPrice: 4890000,
    rating: 4.7,
    reviews: 71,
    stock: 12,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#FFB85C',
    panel: '#372414',
    specs: [
      {label: 'SoC', value: 'RK3588 octa-core'},
      {label: 'Memory', value: '8GB LPDDR4X'},
      {label: 'Storage', value: 'eMMC and NVMe support'},
      {label: 'Video', value: '8K decode and dual display'},
    ],
    tags: ['RK3588', 'Edge AI', 'Media'],
    applications: ['Vision node', 'HMI terminal', 'AI gateway'],
    compatibility: ['NVMe SSDs', 'CSI cameras', 'USB accelerators'],
  },
  {
    id: 'rock-5b-vision-gateway',
    code: 'RK5',
    name: 'Rock 5B Vision Gateway',
    vendor: 'Radxa',
    seller: 'Embedded Shop Labs',
    category: 'sbc',
    highlight: 'High-bandwidth SBC for camera ingest and industrial edge compute',
    shortDescription: 'Radxa Rock 5B tuned for multi-sensor gateways and local analytics.',
    overview:
      'Use this board when you need a compact Linux platform with strong CPU headroom, fast storage, and enough IO for cameras, buses, and analytics sidecars.',
    price: 4890000,
    previousPrice: 5290000,
    rating: 4.8,
    reviews: 83,
    stock: 10,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#5CE4FF',
    panel: '#102A34',
    specs: [
      {label: 'SoC', value: 'RK3588S 8-core'},
      {label: 'Memory', value: '8GB LPDDR4X'},
      {label: 'Storage', value: 'M.2 NVMe ready'},
      {label: 'Networking', value: '2.5GbE and Wi-Fi options'},
    ],
    tags: ['Gateway', 'Vision', 'Radxa'],
    applications: ['Inspection node', 'Edge recorder', 'Robot supervisor'],
    compatibility: ['NVMe drives', 'CSI cameras', 'ROS2 containers'],
  },
  {
    id: 'zynq-7020-vision-accelerator-board',
    code: 'Z7V',
    name: 'Zynq-7020 Vision Accelerator Board',
    vendor: 'AMD Xilinx',
    seller: 'Embedded Shop Labs',
    category: 'fpga',
    highlight: 'Zynq SoC platform for camera timing and hardware acceleration',
    shortDescription: 'Dual-domain board blending ARM software control with FPGA pipelines.',
    overview:
      'A balanced platform for image acquisition, deterministic pre-processing, and custom accelerator experiments where teams need Linux plus programmable fabric.',
    price: 5890000,
    previousPrice: 6290000,
    rating: 4.8,
    reviews: 69,
    stock: 8,
    availability: 'Low stock',
    leadTime: 'Ships in 72h',
    accent: '#7DFF7A',
    panel: '#1A3016',
    specs: [
      {label: 'SoC', value: 'Xilinx Zynq-7020'},
      {label: 'Memory', value: '1GB DDR3'},
      {label: 'Video IO', value: 'HDMI and camera headers'},
      {label: 'Expansion', value: 'PMOD and FMC-lite'},
    ],
    tags: ['Zynq', 'Vision', 'Acceleration'],
    applications: ['Camera bridge', 'Video pre-process', 'Realtime control'],
    compatibility: ['Vivado', 'PetaLinux', 'Sensor mezzanines'],
  },
  {
    id: 'spartan-7-signal-capture-kit',
    code: 'SP7',
    name: 'Spartan-7 Signal Capture Kit',
    vendor: 'AMD Xilinx',
    seller: 'Embedded Shop Labs',
    category: 'fpga',
    highlight: 'Entry FPGA kit for timing capture, buses, and digital interfaces',
    shortDescription: 'Compact Spartan-7 board for logic experiments and deterministic IO.',
    overview:
      'Designed for teams learning HDL or shipping small but strict timing interfaces around encoders, sensors, and low-latency bus handling.',
    price: 3640000,
    previousPrice: 3990000,
    rating: 4.6,
    reviews: 48,
    stock: 19,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#FFD46A',
    panel: '#382C12',
    specs: [
      {label: 'FPGA', value: 'Spartan-7 fabric'},
      {label: 'Clock', value: '100MHz onboard oscillator'},
      {label: 'Debug', value: 'USB JTAG/UART'},
      {label: 'Expansion', value: 'PMOD headers'},
    ],
    tags: ['HDL', 'Timing', 'Capture'],
    applications: ['Bus sniffer', 'Encoder logic', 'Digital interface lab'],
    compatibility: ['PMOD modules', 'ILA debug', 'Vivado'],
  },
  {
    id: 'cyclone-10-lp-logic-trainer',
    code: 'C10',
    name: 'Cyclone 10 LP Logic Trainer',
    vendor: 'Intel PSG',
    seller: 'Embedded Shop Labs',
    category: 'fpga',
    highlight: 'Low-power Intel FPGA board for digital design training and lab bring-up',
    shortDescription: 'Accessible Cyclone 10 platform for signal routing, counters, and control.',
    overview:
      'A practical board for classroom-style HDL exercises and low-power control logic where teams want fast iteration with mature Intel toolchains.',
    price: 3290000,
    previousPrice: 3590000,
    rating: 4.5,
    reviews: 41,
    stock: 17,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#93FFB0',
    panel: '#173122',
    specs: [
      {label: 'FPGA', value: 'Cyclone 10 LP'},
      {label: 'Memory', value: 'Onboard SDRAM'},
      {label: 'Interface', value: 'GPIO, UART, USB Blaster'},
      {label: 'Power', value: 'Low-power lab profile'},
    ],
    tags: ['Intel FPGA', 'Training', 'Control'],
    applications: ['Logic trainer', 'PWM generation', 'State machine lab'],
    compatibility: ['Quartus Prime', 'GPIO daughter cards', 'Signal probes'],
  },
  {
    id: 'differential-drive-robot-base',
    code: 'DDB',
    name: 'Differential Drive Robot Base',
    vendor: 'Motion Axis',
    seller: 'Embedded Shop Labs',
    category: 'robotics',
    highlight: 'Two-wheel mobile base for navigation stacks and control experiments',
    shortDescription: 'Compact differential platform with motor mounts, caster, and payload deck.',
    overview:
      'A practical base for indoor robot demos where you need a stable locomotion platform for lidar, cameras, and compute bring-up without fabricating a chassis from scratch.',
    price: 4290000,
    previousPrice: 4590000,
    rating: 4.7,
    reviews: 55,
    stock: 14,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#63D9FF',
    panel: '#11293A',
    specs: [
      {label: 'Drive', value: '2WD differential base'},
      {label: 'Payload', value: 'Up to 6kg'},
      {label: 'Mounting', value: 'Stacked plate with SBC mounts'},
      {label: 'Power', value: '12V to 24V battery support'},
    ],
    tags: ['Mobile robot', 'Base', 'Navigation'],
    applications: ['SLAM demo', 'Warehouse robot', 'Teaching platform'],
    compatibility: ['Motor drivers', 'Lidar mounts', 'Pi and Jetson kits'],
  },
  {
    id: 'robotic-arm-4dof-kit',
    code: 'A4D',
    name: '4DOF Robotic Arm Starter Kit',
    vendor: 'ServoCraft',
    seller: 'Embedded Shop Labs',
    category: 'robotics',
    highlight: 'Desktop manipulator kit for inverse kinematics and pick-place demos',
    shortDescription: 'Entry robotic arm with controller, joints, and expansion for sensors.',
    overview:
      'Great for manipulation demos, lab automation proofs, and motion programming exercises where teams want a compact arm that can be deployed quickly.',
    price: 4980000,
    previousPrice: 5390000,
    rating: 4.6,
    reviews: 47,
    stock: 11,
    availability: 'In stock',
    leadTime: 'Ships in 72h',
    accent: '#FF9E63',
    panel: '#392012',
    specs: [
      {label: 'Axes', value: '4 controllable joints'},
      {label: 'Reach', value: 'Approx. 380mm'},
      {label: 'Control', value: 'UART and USB interface'},
      {label: 'End effector', value: 'Gripper-ready mount'},
    ],
    tags: ['Manipulator', 'Arm', 'Kinematics'],
    applications: ['Pick and place', 'Teaching robot', 'Bench automation'],
    compatibility: ['Vision cameras', 'Stepper drivers', 'ROS2 bridges'],
  },
  {
    id: 'mecanum-wheel-mobile-platform',
    code: 'MEC',
    name: 'Mecanum Wheel Mobile Platform',
    vendor: 'OmniMotion',
    seller: 'Embedded Shop Labs',
    category: 'robotics',
    highlight: 'Holonomic robot base for omnidirectional motion experiments',
    shortDescription: 'Mecanum platform suited for warehouse navigation and smooth lateral control.',
    overview:
      'Choose this base when your prototype benefits from sideways movement, compact turning, and richer motion control experiments in constrained environments.',
    price: 6120000,
    previousPrice: 6590000,
    rating: 4.8,
    reviews: 62,
    stock: 7,
    availability: 'Low stock',
    leadTime: 'Ships in 72h',
    accent: '#76F5D0',
    panel: '#14332E',
    specs: [
      {label: 'Drive', value: '4-wheel mecanum'},
      {label: 'Payload', value: 'Up to 10kg'},
      {label: 'Control', value: 'Omnidirectional kinematics'},
      {label: 'Mounting', value: 'Layered top deck rails'},
    ],
    tags: ['Mecanum', 'Omni', 'AMR'],
    applications: ['Indoor logistics', 'Research robot', 'Demo platform'],
    compatibility: ['CAN drivers', 'Lidar towers', 'Industrial batteries'],
  },
  {
    id: 'agv-navigation-chassis-pro',
    code: 'AGV',
    name: 'AGV Navigation Chassis Pro',
    vendor: 'Robot Foundry',
    seller: 'Embedded Shop Labs',
    category: 'robotics',
    highlight: 'Heavy-duty mobile base for AGV and autonomous transport prototypes',
    shortDescription: 'Scaled mobile chassis with wiring space, deck mounts, and battery volume.',
    overview:
      'This chassis gives teams a more production-like base for navigation stacks, industrial sensing, and transport robot validation in real workflows.',
    price: 7990000,
    previousPrice: 8590000,
    rating: 4.9,
    reviews: 77,
    stock: 4,
    availability: 'Low stock',
    leadTime: 'Ships in 5 days',
    accent: '#B7FF5A',
    panel: '#223112',
    specs: [
      {label: 'Payload', value: 'Up to 25kg'},
      {label: 'Drive', value: 'Industrial AGV wheelbase'},
      {label: 'Battery bay', value: '24V pack support'},
      {label: 'Mounts', value: 'Lidar, mast, and compute deck'},
    ],
    tags: ['AGV', 'Transport', 'Autonomy'],
    applications: ['Factory robot', 'Logistics demo', 'Navigation stack'],
    compatibility: ['Lidar modules', 'Fleet gateways', 'CAN motion systems'],
  },
  {
    id: 'industrial-tof-depth-sensor',
    code: 'TOF',
    name: 'Industrial ToF Depth Sensor',
    vendor: 'Optic Motion',
    seller: 'Embedded Shop Labs',
    category: 'sensors',
    highlight: 'Time-of-flight module for depth-aware machine and robot perception',
    shortDescription: 'Compact depth sensor for obstacle measurement and near-field ranging.',
    overview:
      'A useful sensor for short-range depth capture, collision avoidance, and industrial inspection zones where simple and stable distance measurement is needed.',
    price: 2760000,
    previousPrice: 2990000,
    rating: 4.7,
    reviews: 53,
    stock: 18,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#6EE3FF',
    panel: '#143040',
    specs: [
      {label: 'Range', value: '0.1m to 6m'},
      {label: 'Interface', value: 'USB and UART'},
      {label: 'Frame rate', value: 'Up to 30fps'},
      {label: 'Use case', value: 'Short-range depth map'},
    ],
    tags: ['Depth', 'ToF', 'Perception'],
    applications: ['Obstacle sensing', 'Bin detection', 'Distance measurement'],
    compatibility: ['ROS2 depth nodes', 'Pi 5', 'Jetson kits'],
  },
  {
    id: 'imu-9axis-motion-module',
    code: 'IMU',
    name: 'IMU 9-axis Motion Module',
    vendor: 'Sense Matrix',
    seller: 'Embedded Shop Labs',
    category: 'sensors',
    highlight: 'Inertial sensor board for orientation, stabilization, and fusion pipelines',
    shortDescription: 'Compact 9-axis IMU module for motion tracking and navigation experiments.',
    overview:
      'A low-footprint sensor for attitude estimation, stabilization loops, and fused navigation stacks that need dependable inertial input.',
    price: 890000,
    previousPrice: 990000,
    rating: 4.5,
    reviews: 72,
    stock: 42,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#B39BFF',
    panel: '#241A39',
    specs: [
      {label: 'Sensors', value: '3-axis gyro, accel, magnetometer'},
      {label: 'Interface', value: 'I2C and SPI'},
      {label: 'Output', value: 'Quaternion and raw data ready'},
      {label: 'Power', value: '3.3V logic friendly'},
    ],
    tags: ['IMU', 'Fusion', 'Motion'],
    applications: ['Robot balance', 'Orientation tracking', 'Navigation'],
    compatibility: ['MCU boards', 'Pi HATs', 'ROS2 sensor fusion'],
  },
  {
    id: 'thermal-inspection-camera-board',
    code: 'THM',
    name: 'Thermal Inspection Camera Board',
    vendor: 'InfraSight',
    seller: 'Embedded Shop Labs',
    category: 'sensors',
    highlight: 'Thermal imaging module for machine diagnostics and safety monitoring',
    shortDescription: 'Compact thermal board for hotspot detection and maintenance workflows.',
    overview:
      'Useful for predictive maintenance, safety audits, and embedded inspection systems where teams need lightweight thermal awareness on the edge.',
    price: 4190000,
    previousPrice: 4490000,
    rating: 4.7,
    reviews: 38,
    stock: 6,
    availability: 'Low stock',
    leadTime: 'Ships in 72h',
    accent: '#FF8C7C',
    panel: '#391D18',
    specs: [
      {label: 'Sensor', value: 'LWIR thermal array'},
      {label: 'Output', value: 'USB or SPI stream'},
      {label: 'Applications', value: 'Inspection and hotspot monitoring'},
      {label: 'Mounting', value: 'Compact board-level module'},
    ],
    tags: ['Thermal', 'Inspection', 'Safety'],
    applications: ['Hotspot detection', 'Motor inspection', 'Thermal analytics'],
    compatibility: ['Pi 5', 'Jetson', 'Inspection dashboards'],
  },
  {
    id: 'relay-control-board-8ch',
    code: 'REL',
    name: '8-Channel Relay Control Board',
    vendor: 'BusWorks',
    seller: 'Embedded Shop Labs',
    category: 'power',
    highlight: 'Multi-channel relay module for switching loads and actuators',
    shortDescription: 'Practical 8-channel relay board for cabinet control and automation labs.',
    overview:
      'A straightforward expansion module for controlling lamps, pumps, relays, and low-speed machine actions from an SBC or microcontroller.',
    price: 980000,
    previousPrice: 1090000,
    rating: 4.4,
    reviews: 57,
    stock: 27,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#68E1FF',
    panel: '#16303A',
    specs: [
      {label: 'Channels', value: '8 relay outputs'},
      {label: 'Control', value: '3.3V and 5V logic compatible'},
      {label: 'Load', value: 'Suitable for switching AC/DC loads'},
      {label: 'Terminals', value: 'Screw terminal wiring'},
    ],
    tags: ['Relay', 'Switching', 'Automation'],
    applications: ['Cabinet IO', 'Lab automation', 'Remote switching'],
    compatibility: ['Raspberry Pi', 'STM32 boards', 'DIN wiring harnesses'],
  },
  {
    id: 'smart-battery-management-module',
    code: 'BMS',
    name: 'Smart Battery Management Module',
    vendor: 'PowerCore',
    seller: 'Embedded Shop Labs',
    category: 'power',
    highlight: 'Monitoring and protection module for robot and portable power packs',
    shortDescription: 'Battery management board with balancing, telemetry, and fault handling.',
    overview:
      'A strong fit for mobile robots and portable field systems that need pack monitoring, safer charging workflows, and battery health visibility.',
    price: 1860000,
    previousPrice: 2040000,
    rating: 4.6,
    reviews: 46,
    stock: 14,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#A7FF5C',
    panel: '#223214',
    specs: [
      {label: 'Function', value: 'Pack balancing and protection'},
      {label: 'Telemetry', value: 'Voltage, current, temperature'},
      {label: 'Use case', value: 'Robot battery packs'},
      {label: 'Interface', value: 'UART and CAN options'},
    ],
    tags: ['Battery', 'Power', 'Protection'],
    applications: ['AMR battery pack', 'Portable compute', 'Field power'],
    compatibility: ['24V packs', 'Monitoring dashboards', 'CAN nodes'],
  },
  {
    id: 'din-rail-power-monitor',
    code: 'DIN',
    name: 'DIN Rail Power Supply Monitor',
    vendor: 'PowerRail',
    seller: 'Embedded Shop Labs',
    category: 'power',
    highlight: 'Cabinet-friendly power monitor for industrial rails and field systems',
    shortDescription: 'DIN-mount module for voltage, current, and status monitoring in enclosures.',
    overview:
      'Designed for cabinet builders and gateway teams that need quick visibility into rail health, load conditions, and supply faults without overcomplicating deployment.',
    price: 1540000,
    previousPrice: 1690000,
    rating: 4.5,
    reviews: 33,
    stock: 20,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#FFD36B',
    panel: '#372C14',
    specs: [
      {label: 'Mounting', value: 'DIN rail enclosure'},
      {label: 'Monitoring', value: 'Voltage, current, alarms'},
      {label: 'Interface', value: 'Modbus or discrete alerts'},
      {label: 'Power range', value: '12V to 48V systems'},
    ],
    tags: ['DIN rail', 'Power', 'Monitoring'],
    applications: ['Control cabinet', 'Gateway rack', 'Supply diagnostics'],
    compatibility: ['Industrial PSUs', 'PLC enclosures', 'Alarm systems'],
  },
  {
    id: 'industrial-rs485-can-gateway',
    code: 'R45',
    name: 'Industrial RS485/CAN Gateway',
    vendor: 'BusLink',
    seller: 'Embedded Shop Labs',
    category: 'connectivity',
    highlight: 'Bridge module for fieldbus integration across CAN and RS485 devices',
    shortDescription: 'Rugged protocol gateway for machine buses, sensors, and controller edges.',
    overview:
      'Use this when your stack needs to unify legacy serial equipment, CAN nodes, and field diagnostics through one dependable embedded bridge.',
    price: 2390000,
    previousPrice: 2590000,
    rating: 4.7,
    reviews: 66,
    stock: 18,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#7DD4FF',
    panel: '#173041',
    specs: [
      {label: 'Buses', value: 'RS485 and CAN 2.0B'},
      {label: 'Use case', value: 'Protocol translation and bridging'},
      {label: 'Power', value: '9V to 24V DC'},
      {label: 'Mounting', value: 'Industrial panel form factor'},
    ],
    tags: ['Gateway', 'RS485', 'CAN'],
    applications: ['Protocol bridge', 'Machine retrofit', 'Bus diagnostics'],
    compatibility: ['PLC networks', 'Sensor arrays', 'Industrial cabinets'],
  },
  {
    id: 'wifi-6-ble-edge-module',
    code: 'W6B',
    name: 'Wi-Fi 6 + BLE Edge Module',
    vendor: 'LinkForge',
    seller: 'Embedded Shop Labs',
    category: 'connectivity',
    highlight: 'Wireless connectivity module for edge nodes and portable devices',
    shortDescription: 'Compact Wi-Fi 6 and BLE module for high-throughput embedded networking.',
    overview:
      'A convenient module for modern wireless prototypes that need strong local networking, BLE commissioning, and compact integration into edge hardware.',
    price: 1190000,
    previousPrice: 1290000,
    rating: 4.5,
    reviews: 59,
    stock: 26,
    availability: 'In stock',
    leadTime: 'Ships in 24h',
    accent: '#73FFE1',
    panel: '#13332C',
    specs: [
      {label: 'Wireless', value: 'Wi-Fi 6 and BLE 5'},
      {label: 'Interface', value: 'M.2 or board-to-board'},
      {label: 'Throughput', value: 'High-bandwidth edge links'},
      {label: 'Use case', value: 'Gateways and portable devices'},
    ],
    tags: ['Wi-Fi 6', 'BLE', 'Wireless'],
    applications: ['Wireless gateway', 'Portable HMI', 'Sensor uplink'],
    compatibility: ['Linux SBCs', 'MCU host boards', 'Antenna kits'],
  },
  {
    id: 'lora-telemetry-node-board',
    code: 'LRA',
    name: 'LoRa Telemetry Node Board',
    vendor: 'RangeLink',
    seller: 'Embedded Shop Labs',
    category: 'connectivity',
    highlight: 'Long-range telemetry node for sparse field data and remote sensing',
    shortDescription: 'LoRa-ready board for remote monitoring, low-power reporting, and telemetry.',
    overview:
      'A good fit for distributed sensor networks where payloads are light, battery life matters, and infrastructure is limited or spread over larger sites.',
    price: 1420000,
    previousPrice: 1560000,
    rating: 4.6,
    reviews: 43,
    stock: 21,
    availability: 'In stock',
    leadTime: 'Ships in 48h',
    accent: '#C5FF71',
    panel: '#263316',
    specs: [
      {label: 'Radio', value: 'LoRa long-range telemetry'},
      {label: 'Power', value: 'Low-power field deployment'},
      {label: 'IO', value: 'Sensor header and serial interface'},
      {label: 'Use case', value: 'Remote telemetry node'},
    ],
    tags: ['LoRa', 'Telemetry', 'Remote IO'],
    applications: ['Field sensors', 'Environmental logging', 'Utility monitoring'],
    compatibility: ['Battery packs', 'External antennas', 'MCU gateways'],
  },
  {
    id: 'router-hat-5g-sbc',
    code: '5GH',
    name: '5G Router HAT for SBC',
    vendor: 'WaveLink',
    seller: 'Embedded Shop Labs',
    category: 'connectivity',
    highlight: 'Cellular networking HAT for field-deployed single-board systems',
    shortDescription: '5G-ready router HAT for SBC gateways, remote access, and mobile deployment.',
    overview:
      'This add-on gives edge gateways a clean path to cellular connectivity for remote diagnostics, telemetry backhaul, and field deployment in infrastructure-light environments.',
    price: 3690000,
    previousPrice: 3990000,
    rating: 4.7,
    reviews: 52,
    stock: 8,
    availability: 'Low stock',
    leadTime: 'Ships in 72h',
    accent: '#69C4FF',
    panel: '#14283B',
    specs: [
      {label: 'Connectivity', value: '5G/LTE backhaul'},
      {label: 'Form factor', value: 'HAT for SBC platforms'},
      {label: 'Use case', value: 'Field router and remote diagnostics'},
      {label: 'Antenna', value: 'External antenna connectors'},
    ],
    tags: ['5G', 'Backhaul', 'Gateway'],
    applications: ['Remote gateway', 'Vehicle edge', 'Field telemetry'],
    compatibility: ['Raspberry Pi', 'Industrial enclosures', 'External antennas'],
  },
];
